# Generated by Django 3.1.5 on 2021-02-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espaco_Tao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='descricao',
            field=models.TextField(blank=True, default=None, help_text='Aqui comente sobre o que e/ou como é realiado essa modalidade'),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='modalidade',
            field=models.CharField(choices=[('', ''), ('Terapia', 'Terapia'), ('Tai Chi Chuan', 'Tai Chi Chuan'), ('Cone Hindu', 'Cone Hindu'), ('Barras de Access', 'Barras de Access')], default=None, max_length=30, unique=True),
        ),
    ]
