# Generated by Django 3.1.5 on 2021-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espaco_Tao', '0002_auto_20210208_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('', ''), ('solteiro(a)', 'Solteiro(a)'), ('casado(a)', 'Casado(a)'), ('divorciado(a)', 'Divorciado(a)'), ('viúvo(a)', 'Viúvo(a)')], default='solterio(a)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(default='', help_text='Campo obrigatório*'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, choices=[('', ''), ('desempregado', 'Desempregado'), ('empregado', 'Empregado')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='modalidade',
            field=models.CharField(choices=[('', ''), ('Terapia Transpessoal', 'Terapia Transpessoal'), ('Tai Chi Chuan', 'Tai Chi Chuan'), ('Cone Hindu', 'Cone Hindu'), ('Barras de Access', 'Barras de Access')], default=None, max_length=30, unique=True),
        ),
    ]
